export const arrCompany = [
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  },
  {
    name: 'Google Company',
    address: '590 Cách Mạng Tháng 8, Phường 11, Quận 3, TP. Hồ Chí Minh ',
    website: 'google.com.vn',
    zipCode: '123456',
    dateCreate: new Date(),
    telPhone: '08.696969',
  }
];
